name = "VanillaishCreate"
author = "crew"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15c3a13063fb14f62310e6ba656d7c9b01d13031515ec1b39aff706a9f3efcfd"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
