name = "VanillaishCreate"
author = "crew"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f97ae84f4f7b22a887b1fcef53de0a5ef90f21ac0b92ec1c6c6c967ee0399fe2"

[versions]
forge = "43.1.65"
minecraft = "1.19.2"
